name: wikwok
description: Doomscroll your way to endless knowledge.
publish_to: none
version: 1.5.5+26
environment:
  sdk: ^3.5.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  dio: ^5.8.0+1
  flutter_bloc: ^9.0.0
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.3
  collection: ^1.19.1
  package_info_plus: ^9.0.0
  cached_network_image: ^3.4.1
  forui: ^0.16.0
  flutter_svg: ^2.2.1
  connectivity_plus: ^7.0.0
  share_plus: ^11.1.0
  flutter_animate: ^4.5.2
  rxdart: ^0.28.0
  flutter_native_splash: ^2.4.7
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_gen_runner: ^5.12.0
  build_runner: ^2.9.0
flutter:
  generate: true
  uses-material-design: true
  assets:
  - assets/
