name: Analyze code

on:
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.35.5

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: 'ğŸ“„ Format code'
        run: dart format -o none --set-exit-if-changed .

      - name: 'ğŸ› ï¸ Fix code'
        run: dart fix --dry-run

      - name: 'ğŸ” Analyze code'
        run: dart analyze