name: On pull request

on:
  pull_request:

jobs:
  get-flutter-sdk-version:
    uses: ./.github/workflows/get-flutter-sdk-version.yml

  test:
    needs: [ get-flutter-sdk-version ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Flutter (${{ needs.get-flutter-sdk-version.outputs.version }})
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ needs.get-flutter-sdk-version.outputs.version }}

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: 'ğŸ§ª Run tests'
        run: flutter test lib --exclude-tags "integration"

  format:
    needs: [ get-flutter-sdk-version ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter (${{ needs.get-flutter-sdk-version.outputs.version }})
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ needs.get-flutter-sdk-version.outputs.version }}

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: 'ğŸ“„ Format code'
        run: dart format -o none --set-exit-if-changed .

      - name: 'ğŸ› ï¸ Fix code'
        run: dart fix --dry-run
