name: On pull request

on:
  pull_request:

jobs:
  get-flutter-sdk-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get.outputs.version }}
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - id: get
        run: |
          version=$(python3 _scripts/get_flutter_sdk_version.py)
          echo "VERSION=$version" >> $GITHUB_OUTPUT

      # echo the version for debug purposes
      - run: echo ${{ steps.get.outputs.version }}

  test:
    needs: [ get-flutter-sdk-version ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Flutter (version ${{ needs.get-flutter-sdk-version.version }})
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ needs.get-flutter-sdk-version.version }}

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: 'ğŸ§ª Run tests'
        run: flutter test lib --exclude-tags "integration"

  format:
    needs: [ get-flutter-sdk-version ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter (${{ needs.get-flutter-sdk-version.version }})
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ needs.get-flutter-sdk-version.version }}

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: 'ğŸ“„ Format code'
        run: dart format -o none --set-exit-if-changed .

      - name: 'ğŸ› ï¸ Fix code'
        run: dart fix --dry-run
