name: Bump version and prepare release

on:
  workflow_dispatch:
    inputs:
      part:
        description: "The part of the version to bump"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}
      - uses: actions/checkout@v5
        with:
          token: ${{ steps.app.outputs.token }}
          fetch-depth: 0
      - run: |
          python -m venv _scripts/venv
          source _scripts/venv/bin/activate
          pip install -r _scripts/requirements.txt
          python _scripts/bump_version_in_pubspec.py --${{ inputs.part }} --file pubspec.yaml
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add pubspec.yaml
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "Bump version and build number"
          git push origin HEAD:${GITHUB_REF#refs/heads/}

  create-release:
    needs: [bump]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - id: app-version
        uses: ./.github/actions/get-app-version
      - run: |
          gh release create v${{ steps.app-version.outputs.version }} --latest=false --generate-notes --prerelease --latest=false
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
