name: Publish build from release

on:
  release:
    types: [ published, edited ]

permissions:
  contents: write

jobs:
  get-flutter-sdk-version:
    uses: ./.github/workflows/flutter-sdk-version.yml

  build:
    needs: [ get-flutter-sdk-version ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup Flutter (${{ needs.get-flutter-sdk-version.outputs.version }})
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ needs.get-flutter-sdk-version.outputs.version }}
          cache: true

      - run: flutter pub get

      - run: dart run build_runner build

      - run: find . -name '*_test.dart' -delete

      - env:
          KEYSTORE_JKS: ${{ secrets.KEYSTORE_JKS }}
          KEY_PROPERTIES: ${{ secrets.KEY_PROPERTIES }}
        run: |
          echo $KEYSTORE_JKS | base64 -d > android/app/keystore.jks
          echo $KEY_PROPERTIES | base64 -d > android/key.properties

      - run: |
          flutter build apk --release --target-platform android-arm64
          mv build/app/outputs/flutter-apk/app-release.apk .

      - uses: actions/upload-artifact@v4
        with:
          name: apk
          path: app-release.apk

  upload-to-release:
    needs: [ build ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - run: |
          VERSION=${{ github.ref_name }}
          APP_VERSION=${VERSION#v}
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV

      - uses: actions/download-artifact@v5
        with:
          name: apk

      - run: |
          mv app-release.apk wikwok-${{ env.APP_VERSION }}.apk

      - run: |
          gh release upload ${{github.event.release.tag_name}} wikwok-${{ env.APP_VERSION }}.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash