name: Run unit and widget tests

on:
  pull_request:

jobs:
  get-flutter-sdk-version:
    uses: ./.github/workflows/flutter-sdk-version.yml

  test:
    needs: [ get-flutter-sdk-version ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Flutter (${{ needs.get-flutter-sdk-version.outputs.version }})
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ needs.get-flutter-sdk-version.outputs.version }}
          cache: true

      - run: flutter pub get

      - run: dart run build_runner build

      - run: flutter test lib --exclude-tags "integration"